// ------------------ Организация массива данных для товаров ------------------ //

export const productsArr = [
    {
        "nameProduct": "Macbook Air M1 13\" 8Gb 256Gb",
        "brand": "Apple",
        "display": "13",
        "ram": "8",
        "storage": "256",
        "color": "grey",
        "price": "999",
        "year": "2020",
        "amount": "5",
        "img": "./assets/images/macbook-air-8-256.jpeg"
    },
    {
        "nameProduct": "Macbook Pro M1 13\" 16Gb 256Gb",
        "brand": "Apple",
        "display": "13",
        "ram": "16",
        "storage": "256",
        "color": "silver",
        "price": "1299",
        "year": "2020",
        "amount": "4",
        "img": "./assets/images/macbook-pro-16-256.png"
    },
    {
        "nameProduct": "Macbook Pro M1 16\" 16Gb 512Gb",
        "brand": "Apple",
        "display": "16",
        "ram": "16",
        "storage": "512",
        "color": "grey",
        "price": "1999",
        "year": "2020",
        "amount": "2",
        "img": "./assets/images/macbook-pro-16-512.jpeg"
    },
    {
        "nameProduct": "Macbook Pro M2 14\" 16Gb 1Tb",
        "brand": "Apple",
        "display": "14",
        "ram": "16",
        "storage": "1024",
        "color": "silver",
        "price": "1799",
        "year": "2022",
        "amount": "9",
        "img": "./assets/images/macbook-pro-14-1024.png"
    },
    {
        "nameProduct": "HP Victus 16\" 16Gb 512Gb",
        "brand": "HP",
        "display": "16",
        "ram": "16",
        "storage": "512",
        "color": "black",
        "price": "1050",
        "year": "2021",
        "amount": "11",
        "img": "./assets/images/hp-victus-16-512.jpeg"
    },
    {
        "nameProduct": "HP Pavilion 15\" 8Gb 512Gb",
        "brand": "HP",
        "display": "15",
        "ram": "8",
        "storage": "512",
        "color": "black",
        "price": "1350",
        "year": "2021",
        "amount": "10",
        "img": "./assets/images/hp-pavilion-8-512.jpeg"
    },
    {
        "nameProduct": "HP ProBook 14\" 16Gb 256Gb",
        "brand": "HP",
        "display": "14",
        "ram": "16",
        "storage": "256",
        "color": "silver",
        "price": "1090",
        "year": "2021",
        "amount": "15",
        "img": "./assets/images/hp-probook-16-256.jpg"
    },
    {
        "nameProduct": "HP EliteBook 16\" 16Gb 1Tb",
        "brand": "HP",
        "display": "16",
        "ram": "16",
        "storage": "1Tb",
        "color": "silver",
        "price": "1700",
        "year": "2022",
        "amount": "2",
        "img": "./assets/images/hp-elitebook-16-512.jpg"
    },
    {
        "nameProduct": "ASUS ZenBook 13\" 8Gb 256Gb",
        "brand": "ASUS",
        "display": "13",
        "ram": "8",
        "storage": "256",
        "color": "black",
        "price": "890",
        "year": "2021",
        "amount": "21",
        "img": "./assets/images/asus-zenbook-8-256.jpg"
    },
    {
        "nameProduct": "ASUS VivoBook 15\" 8Gb 256Gb",
        "brand": "ASUS",
        "display": "15",
        "ram": "8",
        "storage": "256",
        "color": "grey",
        "price": "700",
        "year": "2020",
        "amount": "19",
        "img": "./assets/images/asus-vivobook-8-256.jpg"
    },
    {
        "nameProduct": "ASUS RogStrix 16\" 16Gb 1Tb",
        "brand": "ASUS",
        "display": "16",
        "ram": "16",
        "storage": "1024",
        "color": "black",
        "price": "1800",
        "year": "2022",
        "amount": "9",
        "img": "./assets/images/asus-rogstrix-16-1Tb.webp"
    },
    {
        "nameProduct": "ASUS Tuf Gaming Dash 16\" 16Gb 512Gb",
        "brand": "ASUS",
        "display": "16",
        "ram": "16",
        "storage": "512",
        "color": "black",
        "price": "1590",
        "year": "2022",
        "amount": "8",
        "img": "./assets/images/asus-tuf-16-512.webp"
    },
    {
        "nameProduct": "Lenovo Legion 16\" 16Gb 512Gb",
        "brand": "Lenovo",
        "display": "16",
        "ram": "16",
        "storage": "512",
        "color": "grey",
        "price": "2050",
        "year": "2022",
        "amount": "18",
        "img": "./assets/images/lenovo-legion-16-1024.jpg"
    },
    {
        "nameProduct": "Lenovo Ideapad 15\" 8Gb 256Gb",
        "brand": "Lenovo",
        "display": "15",
        "ram": "8",
        "storage": "256",
        "color": "silver",
        "price": "880",
        "year": "2020",
        "amount": "13",
        "img": "./assets/images/lenovo-ideapad-8-256.jpg"
    },
    {
        "nameProduct": "Lenovo V14 14\" 8Gb 256Gb",
        "brand": "Lenovo",
        "display": "14",
        "ram": "8",
        "storage": "256",
        "color": "black",
        "price": "680",
        "year": "2020",
        "amount": "11",
        "img": "./assets/images/lenovo-V14-8-256.jpg"
    },
    {
        "nameProduct": "Lenovo ThinkBook 14\" 16Gb 512Gb",
        "brand": "Lenovo",
        "display": "14",
        "ram": "16",
        "storage": "512",
        "color": "grey",
        "price": "1000",
        "year": "2021",
        "amount": "20",
        "img": "./assets/images/lenovo-thinkbook-16-512.jpg"
    },
    {
        "nameProduct": "Dell Vostro 16\" 16Gb 1Tb",
        "brand": "Dell",
        "display": "16",
        "ram": "16",
        "storage": "1024",
        "color": "silver",
        "price": "1590",
        "year": "2022",
        "amount": "16",
        "img": "./assets/images/dell-vostro-16-1024.jpg"
    },
    {
        "nameProduct": "Dell Latitude 15\" 16Gb 512Gb",
        "brand": "Dell",
        "display": "15",
        "ram": "16",
        "storage": "512",
        "color": "black",
        "price": "1490",
        "year": "2021",
        "amount": "24",
        "img": "./assets/images/dell-latitude-16-512.jpg"
    },
    {
        "nameProduct": "Dell Vostro 13\" 8Gb 256gb",
        "brand": "Dell",
        "display": "13",
        "ram": "8",
        "storage": "256",
        "color": "silver",
        "price": "750",
        "year": "2020",
        "amount": "13",
        "img": "./assets/images/dell-vostro-8-256.jpg"
    },
    {
        "nameProduct": "Dell XPS 14\" 8Gb 512Gb",
        "brand": "Dell",
        "display": "14",
        "ram": "8",
        "storage": "512",
        "color": "grey",
        "price": "1980",
        "year": "2022",
        "amount": "2",
        "img": "./assets/images/dell-latitude-16-512.jpg"
    },
    {
        "nameProduct": "Dell Vostro 13\" 8Gb 512gb",
        "brand": "Dell",
        "display": "13",
        "ram": "8",
        "storage": "512",
        "color": "silver",
        "price": "850",
        "year": "2020",
        "amount": "18",
        "img": "./assets/images/dell-vostro-8-256.jpg"
    }
  ]